services:
  db:
    image: postgres:13
    env_file:
      - ./env/db.env
    volumes:
      - db:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./env/adminer.env
    depends_on:
      - db

  app:
    build: app
    restart: always
    privileged: true
    command: npm run dev
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
  
  api:
    build: api
    restart: always
    privileged: true
    command: nodemon index.js
    ports:
      - 3000:3000
    env_file:
      - ./env/api.env
    volumes:
      - ./api:/api

volumes:
  db: