services:
  db:
    image: postgres:13
    env_file:
      - ./env/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin.env
    ports:
      - "5050:80"

volumes:
  postgres_data: