services:
  db:
    image: postgres:13
    env_file:
      - ./env/db.env
    volumes:
      - db:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./env/adminer.env
    depends_on:
      - db

  app:
    build: app
    restart: always
    ports:
      - 8000:8000

volumes:
  db: